namespace Dgmjr.DtoGenerator.AiGenerated;

public partial class DtoGenerator
{
    private const string GenerateDtoAttributeName = "GenerateDtoAttribute";
    private const string GenerateDtoAttributeFilename = GenerateDtoAttributeName + ".g.cs";
    private static readonly string GenerateDtoAttributeDeclaration =
@$"/*
 *  <auto-generated>
 *     This file was generated by {ThisAssembly.Info.Title}.
 *     Any changes made directly to this file will be lost when the code is regenerated.
 * </auto-generated>
 *
 *  {GenerateDtoAttributeName}.cs
 *    Generated: {DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss zzz}
 */
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
[global::System.Diagnostics.Conditional(""CodeGeneration"")]
[global::Microsoft.CodeAnalysis.Diagnostics.SuppressMessage(""Style"", ""IDE1006:Naming Styles"", Justification = ""This is a code generation attribute."")]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute((""{ThisAssembly.Info.Title}"", ""{ThisAssembly.Info.Version}"")]
public sealed class GenerateDtoAttribute : global::System.Attribute
{{
    public GenerateDtoAttribute()
    {{
    }}
}}";
}
